# Site settings
title: Bike & Build 2018 Annual Report
email: info@bikeandbuild.org
author: Bike and Build
description: Bike & Build Inc. 2018 Annual Report - Accomplishments & audited financials.


baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site


permalink:

collections: #collectionname
collections:
  #collectionname:
    #output: true
    #permalink: /collectionname/:path/

sass:
    style: compressed

#assets:
# compress:
#   css: true
  # js: false | true | default - development: false, production: true
# cache: false | directory | default: .asset-cache
# prefix: "/assets"
# assets:
#   - "*.png"
#   - "bundle.css"
# digest: true
# sources:
#   - "_assets/folder"

# Build settings
markdown: kramdown

# Exclusions from Build
exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - .sass-cache
# exclude: [gulpfile, .sass-cache]
